### PR TITLE
Add pyup support, with badges

### PR DESCRIPTION
**Pull request by stephendonner**
r?  @mozilla/firefox-test-engineering

### CODE REVIEW

**Comment by greysteil** [comment]
If you have any trouble with pyup support for Pipenv please do give [Dependabot](https://dependabot.com), the tool I've built, a try. I've been contributing to pipenv to get it perfect.

**Comment by stephendonner** [comment]
Thanks, @greysteil - we'd love it if it you could update the meta SHA hash in the Pipfile.lock for each dependency auto-update PR; can/do you, unlike p y u p.io (not calling them out ❤️ )?

**Comment by greysteil** [comment]
Yep, we totally do that - you can see some of the PRs Dependabot has generated for a project with Pipfile [here](https://github.com/skylines-project/skylines/pulls?q=is%3Apr+is%3Aclosed).

**Comment by davehunt** [comment]
pyup do this too, I think what @stephendonner meant was does Dependabot add/remove transient dependency changes between versions of direct dependencies? For example, if package `foo` v1.0 depends on `bar`, and then `foo` v2.0 drops the dependency on `bar` but adds a dependency on `baz`. Would Dependabot's PR for `foo` v2.0 update the `Pipfile.lock` so that it reflects the entire dependency graph as a result of the update?

**Comment by greysteil** [comment]
Yes, absolutely - [here's](https://github.com/skylines-project/skylines/pull/872/files) a good example.

You can see the code we run to generate those PRs [here](https://github.com/dependabot/dependabot-core/blob/master/lib/dependabot/file_updaters/python/pip/pipfile_file_updater.rb#L78-L95) - it involves a lot of shelling out to Pipenv. Unlike pyup we can evaluate arbitrary code safely ('cos we've been doing it for ages for Ruby updates).

**Comment by davehunt** [comment]
That's impressive, thanks @greysteil. Could you look into trying Dependabot out for one of our repos @stephendonner?

**Comment by stephendonner** [comment]
@davehunt yup; will do!

**Pull request merged**
