### PR TITLE
Add (higher) --priority as 1 (rather than 5), for API-initiated tests

### PR DESCRIPTION
**Pull request by stephendonner**
See https://www.webpagetest.org/forums/archive/index.php?thread-12060.html and ```--priority``` here: https://github.com/marcelduran/webpagetest-api/blob/9c4d4d89aa9637319bdc4d170211e19abafafda7/README.md#test-works-for-test-command-only

@davehunt r, thoughts?  @soulgalore

### CODE REVIEW

**Comment by stephendonner** [comment]
Tested and working; see the "P1, 3" values in this screenshot:

screen shot 2018-12-10 at 2 59 56 pm

**Comment by davehunt** [comment]
Does this mean that users will not be able to trigger a manual test if there's a queue of automated tests? Is that what we want?

**Comment by stephendonner** [comment]
@davehunt the ability to trigger (to get into the queue) will remain the same, AFAICT, but how it's prioritized once queued, will favorable change (I don't claim to know about the internal algorithm).

As I'm investigating the twitch.tv issue(s), I don't want any one-off runs potentially slowing down/causing issues for, an API run.

https://www.webpagetest.org/forums/archive/index.php?thread-12060.html

**Comment by soulgalore** [comment]
Another way to do it could also be have another agent instance (with different key) for one-offs, like a dedicated agent?

**Pull request merged**
